yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):

    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'Группа {self.title}'


class Post(models.Model):
    OUTPUT_OF_POSTS: int = 10

    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )

    class Meta:
        ordering = ['-pub_date']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Group, Post


def index(request):
    posts = Post.objects.select_related('group')[:Post.OUTPUT_OF_POSTS]
    context = {
        'posts': posts,
        'title': 'Последние обновления на сайте'
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:Post.OUTPUT_OF_POSTS]
    context = {
        'group': group,
        'posts': posts
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <body>
    <head>
        <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/x-icon" href={% static 'img/fav/favicon' %}>
        <link rel="apple-touch-icon" sizes="180x180" href={% static 'img/fav/apple-touch-icon.png' %}>
        <link rel="icon" type="image/png" sizes="32x32" href={% static 'img/fav/favicon-32x32.png' %}>
        <link rel="icon" type="image/png" sizes="16x16" href={% static 'img/fav/favicon-16x16.png' %}>
        <meta name="msapplication-TileColor" content="#000">
        <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{% block title %}{% endblock title %}</title>
  <body>
    {% include 'includes/header.html' %}  
    <main>
      <div class="container py-5">
   {% block content %}
   {% endblock content %}
</main>
{% include "includes/footer.html" %}
</body>
</html>

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">© 2020 Copyright 
    <p><span style="color:red">Ya</span>tube</p> 
  </div>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'post:index' %}">
        <img src= {% static "img/logo.png"%} width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>      
</header> 

yatube/templates/includes/post_card.html
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества{% endblock title %}
{% block content %}     
<h1>{{ group.title }} </h1>
<p>{{ group.description }}</p>
{% for post in posts %}
{% include 'includes/post_card.html' %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock content%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте{% endblock title %}
{% block content %}     
<h1>{{ title }}</h1>
{% for post in posts %}
{% include 'includes/post_card.html' %}
{% if post.group %}     
<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %} 
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock content%}